// AUTO-GENERATED by scripts/assemble-sprites.ts — do not edit manually

export interface SpriteRegion {
  /** X position in the sprite sheet */
  x: number
  /** Y position in the sprite sheet */
  y: number
  /** Width of a single frame */
  w: number
  /** Height of a single frame */
  h: number
  /** Number of animation frames (sequential, left to right) */
  frames: number
  /** Milliseconds per frame (0 = static) */
  frameDuration: number
}

export const SPRITE_ATLAS: Record<string, SpriteRegion> = {
  'parent-1-idle': { x: 0, y: 0, w: 32, h: 32, frames: 2, frameDuration: 500 },
  'parent-1-thrust': { x: 64, y: 0, w: 32, h: 32, frames: 3, frameDuration: 100 },
  'parent-1-warp-in': { x: 160, y: 0, w: 32, h: 32, frames: 4, frameDuration: 125 },
  'parent-1-warp-out': { x: 288, y: 0, w: 32, h: 32, frames: 4, frameDuration: 125 },
  'parent-2-idle': { x: 0, y: 32, w: 32, h: 32, frames: 2, frameDuration: 500 },
  'parent-2-thrust': { x: 64, y: 32, w: 32, h: 32, frames: 3, frameDuration: 100 },
  'parent-2-warp-in': { x: 160, y: 32, w: 32, h: 32, frames: 4, frameDuration: 125 },
  'parent-2-warp-out': { x: 288, y: 32, w: 32, h: 32, frames: 4, frameDuration: 125 },
  'parent-3-idle': { x: 0, y: 64, w: 32, h: 32, frames: 2, frameDuration: 500 },
  'parent-3-thrust': { x: 64, y: 64, w: 32, h: 32, frames: 3, frameDuration: 100 },
  'parent-3-warp-in': { x: 160, y: 64, w: 32, h: 32, frames: 4, frameDuration: 125 },
  'parent-3-warp-out': { x: 288, y: 64, w: 32, h: 32, frames: 4, frameDuration: 125 },
  'parent-4-idle': { x: 0, y: 96, w: 32, h: 32, frames: 2, frameDuration: 500 },
  'parent-4-thrust': { x: 64, y: 96, w: 32, h: 32, frames: 3, frameDuration: 100 },
  'parent-4-warp-in': { x: 160, y: 96, w: 32, h: 32, frames: 4, frameDuration: 125 },
  'parent-4-warp-out': { x: 288, y: 96, w: 32, h: 32, frames: 4, frameDuration: 125 },
  'parent-5-idle': { x: 0, y: 128, w: 32, h: 32, frames: 2, frameDuration: 500 },
  'parent-5-thrust': { x: 64, y: 128, w: 32, h: 32, frames: 3, frameDuration: 100 },
  'parent-5-warp-in': { x: 160, y: 128, w: 32, h: 32, frames: 4, frameDuration: 125 },
  'parent-5-warp-out': { x: 288, y: 128, w: 32, h: 32, frames: 4, frameDuration: 125 },
  'parent-6-idle': { x: 0, y: 160, w: 32, h: 32, frames: 2, frameDuration: 500 },
  'parent-6-thrust': { x: 64, y: 160, w: 32, h: 32, frames: 3, frameDuration: 100 },
  'parent-6-warp-in': { x: 160, y: 160, w: 32, h: 32, frames: 4, frameDuration: 125 },
  'parent-6-warp-out': { x: 288, y: 160, w: 32, h: 32, frames: 4, frameDuration: 125 },
  'subagent-1-idle': { x: 0, y: 192, w: 20, h: 20, frames: 2, frameDuration: 500 },
  'subagent-1-thrust': { x: 40, y: 192, w: 20, h: 20, frames: 3, frameDuration: 100 },
  'subagent-1-warp-in': { x: 100, y: 192, w: 20, h: 20, frames: 4, frameDuration: 125 },
  'subagent-1-warp-out': { x: 180, y: 192, w: 20, h: 20, frames: 4, frameDuration: 125 },
  'subagent-2-idle': { x: 0, y: 212, w: 20, h: 20, frames: 2, frameDuration: 500 },
  'subagent-2-thrust': { x: 40, y: 212, w: 20, h: 20, frames: 3, frameDuration: 100 },
  'subagent-2-warp-in': { x: 100, y: 212, w: 20, h: 20, frames: 4, frameDuration: 125 },
  'subagent-2-warp-out': { x: 180, y: 212, w: 20, h: 20, frames: 4, frameDuration: 125 },
  'asteroid-chunky': { x: 0, y: 232, w: 16, h: 16, frames: 2, frameDuration: 500 },
  'asteroid-jagged': { x: 64, y: 232, w: 16, h: 16, frames: 2, frameDuration: 500 },
  'asteroid-smooth': { x: 32, y: 232, w: 16, h: 16, frames: 2, frameDuration: 500 },
  'celestial-gas-giant': { x: 0, y: 248, w: 32, h: 32, frames: 1, frameDuration: 0 },
  'celestial-moon': { x: 64, y: 248, w: 16, h: 16, frames: 1, frameDuration: 0 },
  'celestial-rocky-world': { x: 32, y: 248, w: 32, h: 32, frames: 1, frameDuration: 0 },
  'celestial-space-station': { x: 80, y: 248, w: 48, h: 48, frames: 1, frameDuration: 0 },
  'particle-engine-puff': { x: 0, y: 296, w: 4, h: 4, frames: 3, frameDuration: 166 },
  'particle-spawn-burst': { x: 28, y: 296, w: 8, h: 8, frames: 4, frameDuration: 100 },
  'particle-warp-streak': { x: 12, y: 296, w: 8, h: 2, frames: 2, frameDuration: 150 },
  'effect-bloom-glow': { x: 76, y: 296, w: 16, h: 16, frames: 1, frameDuration: 0 },
  'effect-shooting-star': { x: 60, y: 296, w: 16, h: 4, frames: 1, frameDuration: 0 },
}

export const PARENT_HULL_COUNT = 6
export const SUBAGENT_HULL_COUNT = 2

/** Get sprite region for a parent ship hull (1-indexed) */
export function getParentSprite(hullIndex: number, anim: 'idle' | 'thrust' | 'warp-in' | 'warp-out'): SpriteRegion {
  return SPRITE_ATLAS[`parent-${hullIndex}-${anim}`]
}

/** Get sprite region for a subagent ship hull (1-indexed) */
export function getSubagentSprite(hullIndex: number, anim: 'idle' | 'thrust' | 'warp-in' | 'warp-out'): SpriteRegion {
  return SPRITE_ATLAS[`subagent-${hullIndex}-${anim}`]
}
