// AUTO-GENERATED by scripts/assemble-star-command-sprites.ts — do not edit manually

export interface SpriteRegion {
  /** X position in the sprite sheet */
  x: number
  /** Y position in the sprite sheet */
  y: number
  /** Width of a single frame */
  w: number
  /** Height of a single frame */
  h: number
  /** Number of animation frames (sequential, left to right) */
  frames: number
  /** Milliseconds per frame (0 = static) */
  frameDuration: number
  /** Frames per row for multi-row animations (defaults to frames if unset) */
  framesPerRow?: number
}

export const SC_SPRITE_ATLAS: Record<string, SpriteRegion> = {
  'admiral-alert': { x: 192, y: 0, w: 64, h: 64, frames: 1, frameDuration: 0 },
  'admiral-default': { x: 0, y: 0, w: 64, h: 64, frames: 1, frameDuration: 0 },
  'admiral-speaking': { x: 64, y: 0, w: 64, h: 64, frames: 1, frameDuration: 0 },
  'admiral-standby': { x: 256, y: 0, w: 64, h: 64, frames: 1, frameDuration: 0 },
  'admiral-thinking': { x: 128, y: 0, w: 64, h: 64, frames: 1, frameDuration: 0 },
  'first-officer-default': { x: 320, y: 0, w: 64, h: 64, frames: 1, frameDuration: 0 },
  'first-officer-escalation': { x: 448, y: 0, w: 64, h: 64, frames: 1, frameDuration: 0 },
  'first-officer-idle': { x: 512, y: 0, w: 64, h: 64, frames: 1, frameDuration: 0 },
  'first-officer-working': { x: 384, y: 0, w: 64, h: 64, frames: 1, frameDuration: 0 },
  'crew-cap': { x: 192, y: 64, w: 64, h: 64, frames: 1, frameDuration: 0 },
  'crew-glasses': { x: 256, y: 64, w: 64, h: 64, frames: 1, frameDuration: 0 },
  'crew-headphones': { x: 64, y: 64, w: 64, h: 64, frames: 1, frameDuration: 0 },
  'crew-hoodie': { x: 0, y: 64, w: 64, h: 64, frames: 1, frameDuration: 0 },
  'crew-robot': { x: 128, y: 64, w: 64, h: 64, frames: 1, frameDuration: 0 },
  'crt-corner-bl': { x: 64, y: 128, w: 32, h: 32, frames: 1, frameDuration: 0 },
  'crt-corner-br': { x: 96, y: 128, w: 32, h: 32, frames: 1, frameDuration: 0 },
  'crt-corner-tl': { x: 0, y: 128, w: 32, h: 32, frames: 1, frameDuration: 0 },
  'crt-corner-tr': { x: 32, y: 128, w: 32, h: 32, frames: 1, frameDuration: 0 },
  'crt-edge-h': { x: 128, y: 128, w: 32, h: 8, frames: 1, frameDuration: 0 },
  'crt-edge-v': { x: 160, y: 128, w: 8, h: 32, frames: 1, frameDuration: 0 },
  'crt-scanline': { x: 168, y: 128, w: 32, h: 32, frames: 1, frameDuration: 0 },
  'statusbar-divider': { x: 72, y: 160, w: 4, h: 24, frames: 1, frameDuration: 0 },
  'statusbar-rivet': { x: 64, y: 160, w: 8, h: 8, frames: 1, frameDuration: 0 },
  'statusbar-tile': { x: 0, y: 160, w: 64, h: 24, frames: 1, frameDuration: 0 },
  'chip-dot-active': { x: 124, y: 160, w: 8, h: 8, frames: 1, frameDuration: 0 },
  'chip-dot-complete': { x: 148, y: 160, w: 8, h: 8, frames: 1, frameDuration: 0 },
  'chip-dot-error': { x: 140, y: 160, w: 8, h: 8, frames: 1, frameDuration: 0 },
  'chip-dot-hailing': { x: 132, y: 160, w: 8, h: 8, frames: 1, frameDuration: 0 },
  'chip-dot-idle': { x: 156, y: 160, w: 8, h: 8, frames: 1, frameDuration: 0 },
  'chip-dot-lost': { x: 164, y: 160, w: 8, h: 8, frames: 1, frameDuration: 0 },
  'chip-frame': { x: 76, y: 160, w: 48, h: 20, frames: 1, frameDuration: 0 },
  'shuttle-idle': { x: 0, y: 184, w: 24, h: 24, frames: 1, frameDuration: 0 },
  'shuttle-thrust': { x: 24, y: 184, w: 24, h: 24, frames: 3, frameDuration: 100 },
  'checkmark-holo': { x: 112, y: 208, w: 16, h: 16, frames: 1, frameDuration: 0 },
  'dock-sparkle': { x: 64, y: 208, w: 8, h: 8, frames: 3, frameDuration: 150 },
  'explosion': { x: 0, y: 208, w: 16, h: 16, frames: 4, frameDuration: 100 },
  'gas-puff': { x: 112, y: 184, w: 12, h: 12, frames: 3, frameDuration: 200 },
  'spark': { x: 96, y: 184, w: 8, h: 8, frames: 2, frameDuration: 300 },
  'thruster-flame': { x: 88, y: 208, w: 8, h: 12, frames: 3, frameDuration: 100 },
  'orb-amber': { x: 140, y: 208, w: 12, h: 12, frames: 1, frameDuration: 0 },
  'orb-cargo': { x: 152, y: 208, w: 16, h: 16, frames: 1, frameDuration: 0 },
  'orb-teal': { x: 128, y: 208, w: 12, h: 12, frames: 1, frameDuration: 0 },
  'beacon': { x: 168, y: 208, w: 12, h: 12, frames: 2, frameDuration: 500 },
  'station-hub': { x: 0, y: 224, w: 64, h: 64, frames: 32, frameDuration: 625, framesPerRow: 8 },
}

export const ADMIRAL_VARIANTS = ['default', 'speaking', 'thinking', 'alert', 'standby'] as const
export const FIRST_OFFICER_VARIANTS = ['default', 'working', 'escalation', 'idle'] as const
export const CREW_VARIANTS = ['hoodie', 'headphones', 'robot', 'cap', 'glasses'] as const
